In [182]:
import numpy as np
import seaborn as sns
import pandas as pd

In [184]:
df= pd.read_csv("C:/Users/VINAY KUMAR PATEL/Downloads/machine learning/survey_lung_cancer.csv",header=0)

In [186]:
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  
0                    2                      2           2            1  
1                    2                      2           2            1  
2                    2                      1           2            0  
3                    1                      2           2            0  
4                    2                      1           1            0

In [188]:
df.describe()

AGE     SMOKING  YELLOW_FINGERS     ANXIETY  PEER_PRESSURE  \
count  309.000000  309.000000      309.000000  309.000000     309.000000   
mean    62.673139    1.563107        1.569579    1.498382       1.501618   
std      8.210301    0.496806        0.495938    0.500808       0.500808   
min     21.000000    1.000000        1.000000    1.000000       1.000000   
25%     57.000000    1.000000        1.000000    1.000000       1.000000   
50%     62.000000    2.000000        2.000000    1.000000       2.000000   
75%     69.000000    2.000000        2.000000    2.000000       2.000000   
max     87.000000    2.000000        2.000000    2.000000       2.000000   

       CHRONIC DISEASE    FATIGUE     ALLERGY     WHEEZING  ALCOHOL CONSUMING  \
count       309.000000  309.000000  309.000000  309.000000         309.000000   
mean          1.504854    1.673139    1.556634    1.556634           1.556634   
std           0.500787    0.469827    0.497588    0.497588           0.497588   
min           1.000000    1.000000    1.000000    1.000000           1.000000   
25%           1.000000    1.000000    1.000000    1.000000           1.000000   
50%           2.000000    2.000000    2.000000    2.000000           2.000000   
75%           2.000000    2.000000    2.000000    2.000000           2.000000   
max           2.000000    2.000000    2.000000    2.000000           2.000000   

         COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
count  309.000000           309.000000             309.000000  309.000000   
mean     1.579288             1.640777               1.469256    1.556634   
std      0.494474             0.480551               0.499863    0.497588   
min      1.000000             1.000000               1.000000    1.000000   
25%      1.000000             1.000000               1.000000    1.000000   
50%      2.000000             2.000000               1.000000    2.000000   
75%      2.000000             2.000000               2.000000    2.000000   
max      2.000000             2.000000               2.000000    2.000000   

       LUNG_CANCER  
count   309.000000  
mean      0.873786  
std       0.332629  
min       0.000000  
25%       1.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

In [190]:
df=pd.get_dummies(df).astype(int)

In [192]:
df.head()

AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC DISEASE  \
0   69        1               2        2              1                1   
1   74        2               1        1              1                2   
2   59        1               1        1              2                1   
3   63        2               2        2              1                1   
4   63        1               2        1              1                1   

   FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0         2         1         2                  2         2   
1         2         2         1                  1         1   
2         2         1         2                  1         2   
3         1         1         1                  2         1   
4         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  \
0                    2                      2           2            1   
1                    2                      2           2            1   
2                    2                      1           2            0   
3                    1                      2           2            0   
4                    2                      1           1            0   

   GENDER_F  GENDER_M  
0         0         1  
1         0         1  
2         1         0  
3         0         1  
4         1         0

In [194]:
x=df[['SMOKING']]

In [196]:
y=df['LUNG_CANCER']

In [198]:
x.head()


SMOKING
0        1
1        2
2        1
3        2
4        1

In [200]:
y.head()

0    1
1    1
2    0
3    0
4    0
Name: LUNG_CANCER, dtype: int32

In [202]:
from sklearn.linear_model import LogisticRegression

In [204]:
cls=LogisticRegression()

In [206]:
cls.fit(x,y)

LogisticRegression()

In [208]:
cls.coef_

array([[0.31292114]])

In [210]:
cls.intercept_

array([1.45474418])

In [212]:
from sklearn.model_selection import train_test_split

In [214]:
x_multi = df.drop(columns='LUNG_CANCER')
y_multi = df['LUNG_CANCER']

In [216]:
x_train, x_test, y_train, y_test = train_test_split(x_multi, y_multi, test_size=0.2, random_state=0)

In [218]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(247, 16) (62, 16) (247,) (62,)


In [220]:
cls2 = LogisticRegression(max_iter=1000)

In [222]:
cls2.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [224]:
cls2.coef_

array([[-0.00301871,  0.69876397,  0.75170736,  0.70184036,  0.97202627,
         1.5046467 ,  1.56933078,  1.47220931,  0.53179089,  1.27278471,
         0.96520328,  0.08506104,  1.07877481,  0.40190823, -0.08969212,
         0.08870876]])

In [226]:
cls2.intercept_

array([-15.22591936])

In [228]:
y_pred = cls2.predict(x_test)
print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1]


In [230]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score,accuracy_score
#calculating confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Calculate precision and recall
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
accuracy_score_lr= accuracy_score(y_test, y_pred)

In [232]:
print (conf_matrix)
print(precision)
print(recall)
print(accuracy_score_lr)

[[ 5  5]
 [ 1 51]]
0.9107142857142857
0.9807692307692307
0.9032258064516129


In [234]:
#perform same by lda using train test data

In [236]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [238]:
clf_lda= LinearDiscriminantAnalysis()

In [240]:
clf_lda.fit(x_train,y_train)

LinearDiscriminantAnalysis()

In [242]:
y_pred_lda= clf_lda.predict(x_test)

In [244]:
print(y_pred_lda)

[1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1]


In [246]:
confusion_lda=confusion_matrix(y_test, y_pred_lda)
precision_lda = precision_score(y_test, y_pred_lda)
recall_lda = recall_score(y_test, y_pred_lda)
accuracy_score_lda= accuracy_score(y_test, y_pred_lda)

In [248]:
print (confusion_lda)
print(precision_lda)
print(recall_lda)
print(accuracy_score_lda)


[[ 6  4]
 [ 2 50]]
0.9259259259259259
0.9615384615384616
0.9032258064516129


In [250]:
#perform same by lda using x and y

In [252]:
clf_lda_normal= LinearDiscriminantAnalysis()

In [254]:
clf_lda_normal.fit(x_multi,y_multi)

LinearDiscriminantAnalysis()

In [256]:
y_pred_normal_lda = clf_lda_normal.predict(x_multi)

In [258]:
confusion_matrix_normal=confusion_matrix(y_multi,y_pred_normal_lda)
precision_lda_n = precision_score(y_multi, y_pred_normal_lda)
recall_lda_n = recall_score(y_multi, y_pred_normal_lda)
print(confusion_matrix_normal)
print(precision_lda_n)
print(recall_lda_n)

[[ 28  11]
 [  9 261]]
0.9595588235294118
0.9666666666666667


In [260]:
#perform same by KNN

In [262]:
from sklearn import preprocessing

In [264]:
scaler= preprocessing.StandardScaler().fit(x_train)

In [266]:
x_train_s=scaler.transform(x_train)

In [268]:
scaler= preprocessing.StandardScaler().fit(x_test)

In [270]:
x_test_s=scaler.transform(x_test)

In [272]:
from sklearn.neighbors import KNeighborsClassifier

In [274]:
clf_knn_3= KNeighborsClassifier(n_neighbors=3)

In [276]:
clf_knn_3.fit(x_train_s,y_train)

KNeighborsClassifier(n_neighbors=3)

In [278]:
y_pred_knn= clf_knn_3.predict(x_test_s)

In [280]:
confusion_knn= confusion_matrix(y_test,y_pred_knn)
print(confusion_knn)

[[ 3  7]
 [ 2 50]]


In [287]:
accuracy_score(y_test,y_pred_knn)

0.8548387096774194